services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: Docker_node_app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
